### ISSUE TITLE
第三方库 源码

### ISSUE THREAD

**Issue by liyuping6666** [pigpigyyy/Dorothy-SSR#4]
像libbx.a libsoloud.a很多第三方库 请问一下 这些源码在哪里可以下载 自己编译

**Comment by pigpigyyy** [comment]
bgfx - https://github.com/pigpigyyy/bgfx （在官方源码的基础上调整了stencil mask相关的API功能）
bx - https://github.com/pigpigyyy/bx （为了使Android顺利编译在官方源码的基础上修改了的配置项）
soloud - https://github.com/jarikomppa/soloud （使用官方源码）
sdl2 - https://www.libsdl.org/download-2.0.php （安卓版基于官方源码删除了自动创建gl context的代码部分以兼容bgfx）
http://luajit.org/download.html（使用官方源码）
