### ISSUE TITLE
Content::getFullPath方法有点问题。

### ISSUE THREAD

**Issue by likun123687** [pigpigyyy/Dorothy-SSR#6]
这里是不是应该return fullPath比较好？
https://github.com/pigpigyyy/Dorothy-SSR/blob/fb4cfbe08612a4067621690510a9e9a0a74b6ba9/Source/Basic/Content.cpp#L228

**Comment by pigpigyyy** [comment]
https://github.com/pigpigyyy/Dorothy-SSR/blob/fb4cfbe08612a4067621690510a9e9a0a74b6ba9/Source/Basic/Content.cpp#L222-L226
前面几行已经return fullPath了，如果fullPath为空就返回传入的值。
